### ISSUE TITLE
Auth code expired

### ISSUE THREAD

**Issue by praveen4554** [box/box-node-sdk#97] opened 2016-12-08 19:38 UTC
I am generated authentication using enterpise like the given syntax
sdk.getAppAuthClient('enterprise', id);

It works some time and some time it throws error like auth is expired and can you help me to resolve this issue i am struck in that issue

**Comment by mattwiller** [comment] 2016-12-09 00:09
This is a duplicate of #96 — I'm going to close this one, please see the other issue for any updates

**Closed by mattwiller** 2016-12-09 00:09 UTC
