### ISSUE TITLE
Intermittent "auth code or refresh token expired" error with App Auth client

### ISSUE THREAD

**Issue by sterlingw** [box/box-node-sdk#96] opened 2016-12-07 20:54 UTC
<img width="1051" alt="screen shot 2016-12-07 at 12 45 03 pm" src="https://cloud.githubusercontent.com/assets/8324059/20985865/26533496-bc7b-11e6-85a3-4e5a59267348.png">

Hi there,

My application ocassionally gets this error when calling methods on the box client object that is returned when calling `sdk.getAppAuthClient('user', myAppUserId);`. Is this because I need to create a persistent client? How would I create a persistent app auth client?

This error is intermittent and resolves itself in a seemingly arbitrary amount of time. But it would be more ideal to prevent this error - because until the error is resolved my application is unable to use any of the box client methods.

**Comment by sterlingw** [comment] 2016-12-08 19:13
For more context - this is the actual error, minus headers. This error is returned from calling `boxClient.folders.getItems`:
```
{
    "statusCode":400, 
    "response":{
        "statusCode":400,
        "body":{
            "error":"invalid_grant",
            "error_description":"Current date/time MUST be after or equal to the not-before date/time  listed in the 'nbf' or 'iat' claim"
        },
        "headers": ...
}
```

**Comment by mattwiller** [comment] 2016-12-09 00:11
@sterlingw It turns out that the Box API doesn't currently allow for clock skew when validating the `iat` paranmeter, so if your client's system clock is even a couple seconds ahead of Box's servers, you'll get this error.  I have a PR open (#99) to address this issue by omitting the `iat` parameter by default.  Once that gets merged, I'll cut a new version of the SDK and release it to fix the issue.

**Closed** 2016-12-09 01:19 UTC

**Comment by sterlingw** [comment] 2016-12-09 02:46
@mattwiller great! Looking forward to the next SDK release that includes this fix, as the issue is occurring fairly frequently.

**Comment by arjshiv** [comment] 2016-12-12 22:08
I'm seeing this too - thank you @mattwiller for the fix and we're looking forward to the next SDK release!

@sterlingw thanks for posting this issue!

**Comment by mattwiller** [comment] 2016-12-13 01:17
@sterlingw @arjshiv The latest version of the SDK (v1.2.0) includes a fix for this issue — please try it out and let me know if the problem is still occurring!

**Comment by arjshiv** [comment] 2016-12-13 15:44
@mattwiller will do!

**Comment by sterlingw** [comment] 2016-12-14 00:10
@mattwiller I've updated to the latest version of the SDK and haven't run into this issue since. I'll let ya know if it occurs. Thanks @mattwiller!

@arjshiv I'm glad this was helpful for you!

**Comment by arjshiv** [comment] 2016-12-15 15:41
@mattwiller I've run into this issue once since updating (though it certainly seems to be happening less often). Interestingly, it shows up mainly when we run our Box integration tests on Travis CI - I don't know if that's helpful for you.

**Comment by mattwiller** [comment] 2016-12-15 19:57
@arjshiv Would you mind opening another issue with the contents of the `error` object you're seeing?  Specifically, it would be great if you could include the contents of `error.response.body` for debugging.

**Comment by arjshiv** [comment] 2016-12-15 22:27
@mattwiller Sure -  I'll add in a debug message and create an issue the next time I see it. It's definitely been happening very rarely, but you'll hear from me as soon as we see it :)

**Comment by kabirbaidhya** [comment] 2017-04-01 15:50
**Please Help**. 
Hi I'm getting this error in my application now which is already in production. I've gone through all the related issues in this repository but still can't fix this error. 
```
Expired Auth: Auth code or refresh token has expired.
at Object.buildResponseError (/source/node-api/node_modules/box-node-sdk/lib/util/errors.js:57:23)
at Object.buildExpiredAuthError (/source/node-api/node_modules/box-node-sdk/lib/util/errors.js:70:28)
at /source/node-api/node_modules/box-node-sdk/lib/token-manager.js:211:21
at /source/node-api/node_modules/box-node-sdk/lib/api-request.js:285:3
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)

```
I'm using `getAppAuthClient` to get the client as we're using `enterpriseId` to authenticate with the box.

In my code I've done this:
```javascript
const config = {
    box: {
        clientID: process.env.BOX_CLIENT_ID,
        clientSecret: process.env.BOX_CLIENT_SECRET,
        appAuth: {
            keyID: process.env.BOX_APP_AUTH_KEY_ID,
            privateKey: fs.readFileSync(process.env.BOX_APP_AUTH_PRIVATE_KEY_FILE || defaultPrivateKeyPath),
            passphrase: process.env.BOX_APP_AUTH_PASSPHRASE
        },
        enterpriseId: process.env.BOX_ENTERPRISE_ID
    }
   ...
}
```
```javascript
    let sdk = new BoxSDK(config.box);
    let client = sdk.getAppAuthClient('enterprise', config.box.enterpriseId);

    logger.info('Getting the list of files from the box');

    return new Promise((resolve, reject) => {
        client.folders.getItems(ROOT_FOLDER, {
            fields: 'name,id',
            offset: 0,
            limit: config.fileRetrievalLimit
        }, (err, result) => {
            if (err) {
                logger.error('Error fetching the list', err);
                reject(err);
                return;
            }

            logger.info('Got the file list');
            logger.debug('Results', result);

            resolve(result);
        });
    });
```


If anyone can suggest some workaround to fix this problem it would be really appreciated. 

I'm using  version `1.3.0`
