### ISSUE TITLE
issue: Downloading file, enterprise application (OAUTH with JWT)

### ISSUE THREAD

**Issue by matesio** [box/box-node-sdk#447] opened 2019-10-30 12:43 UTC
I am trying to download files by specific id from the box. Curl command works fine but when I try to do it with Nodejs it shows file now found. I am following official box [documentation](https://developer.box.com/en/reference/get-files-id-content/#request-example).

`var fs = require('fs');
client.files.getReadStream('12345', null, function(error, stream) {

	if (error) {
	    console.log('Error File Download: ', error)
	}
});`

**Error:**
Unexpected API Response [404 Not Found |  not_found - Could not find the specified resource","errorType":"Error","stackTrace":["Object.buildResponseError (/var/task/node_modules/box-node-sdk/lib/util/errors.js:120:23)","Object.buildUnexpectedResponseError (/var/task/node_modules/box-node-sdk/lib/util/errors.js:154:15)","client.get.then.response (/var/task/node_modules/box-node-sdk/lib/managers/files.js:202:18)","tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)","Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:512:31)","Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:569:18)","Promise._settlePromise0 (/var/task/node_modules/bluebird/js/release/promise.js:614:10)","Promise._settlePromises (/var/task/node_modules/bluebird/js/release/promise.js:694:18)","Promise._fulfill (/var/task/node_modules/bluebird/js/release/promise.js:638:18)","Promise._resolveCallback (/var/task/node_modules/bluebird/js/release/promise.js:432:57)","Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:524:17)","Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:569:18)","Promise._settlePromise0 (/var/task/node_modules/bluebird/js/release/promise.js:614:10)","Promise._settlePromises (/var/task/node_modules/bluebird/js/release/promise.js:694:18)","Promise._fulfill (/var/task/node_modules/bluebird/js/release/promise.js:638:18)","Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:582:21)"]}

**Comment by matesio** [comment] 2019-10-30 14:02
If the access token is the developer token then I am not using any access token, I am trying it with AWS lambda with JSON in environment variables.

`const boxConfig = JSON.parse(process.env.BOX_CONFIG);
const sdk = BoxSDK.getPreconfiguredInstance(boxConfig)
const client = sdk.getAppAuthClient('enterprise', boxConfig.enterpriseId);`

**Comment by matesio** [comment] 2019-10-30 14:04
**BOX_CONFIG:**

{
  "boxAppSettings": {
    "clientID": "CL_ID",
    "clientSecret": "C_SECRET",
    "appAuth": {
      "publicKeyID": "PKID",
      "privateKey": "PR_KEY",
      "passphrase": "PASS"
    }
  },
  "enterpriseID": "50790278",
  "webhooks": {
    "primaryKey": "P_KEY",
    "secondaryKey": "S_KEY"
  }
}

**Comment by matesio** [comment] 2019-10-31 07:19
It seems about a custom app, but I am trying with Entreprise application. 
If both work in a similar fashion? Is there any way to access other user's data from service account.

**Comment by cbetta** [comment] 2019-10-31 10:04
@matesio An Enterprise Integration using JWT is pretty much the same as a Custom App using JWT.

And yes, you can either use the As-User header, https://developer.box.com/en/guides/authentication/jwt/as-user/ or use an User Access Token https://developer.box.com/en/guides/authentication/jwt/user-access-tokens/

**Comment by matesio** [comment] 2019-10-31 11:30
@cbetta Thanks for all the help but the guide is much confusing. I would appreciate it if you share a working snippet about how I can configure the enterprise client.

**Comment by cbetta** [comment] 2019-10-31 13:41
You'd have to do this to authenticate as another user using a user access token. 

```
var appUserClient = sdk.getAppAuthClient('user', 'USER-ID');
```

It is important that your application has the right permission for this. You can see those in this guide.

https://developer.box.com/en/guides/authentication/jwt/user-access-tokens/

**Comment by PJSimon** [comment] 2019-11-06 01:19
Hi @matesio,

I just wanted to check in and see if you have made progress on this or still need help.

Thanks!

Patrick

**Comment by PJSimon** [comment] 2020-01-07 05:16
Hi @matesio ,

I'm closing this as it appears resolved, but if you still need help, please just re-open the issue!

Thanks!

Patrick

**Closed by PJSimon** 2020-01-07 05:16 UTC

**Comment by stephencweiss** [comment] 2020-06-16 18:19
> Ok, so you are authenticating using JWT, excellent. In this case, the user you are authenticating as is not you, but a different user, a Service Account. You can find out a lot about this in our docs.
> 
> https://developer.box.com/en/guides/authentication/user-types/app-users/
> 
> You will have to either invite this user to the folder, or use the as-user header.

@PJSimon -- looking at that link, I'm confused as to _how_ to invite the user (the Service Account` user) to be a collaborator. 

I've tried a few things -- for example, I've tried the following with both the `.asUser` line and without:
```
const sdkConfig = require("./box-config.json");
const BoxSDK = require("box-node-sdk");
const sdk = BoxSDK.getPreconfiguredInstance(sdkConfig);
var client = sdk.getAppAuthClient("enterprise");
client.asUser("12620532231");
client.enterprise
  .getUsers()
  .then((users) => console.log(`users --> ${JSON.stringify(users, null, 4)}`))
  .catch(err => console.log(`enterprise err -> ${err}`))

console.log(`\nCurrent User -> ${client.CURRENT_USER_ID}`);
client.users
  .get(client.CURRENT_USER_ID)
  .then((user) =>
    console.log(
      `current user details from Box: ${JSON.stringify(user, null, 4)}`
    )
  )
  .catch((err) => `Error with current user: ${err}`);

client.folders.get("85928103910").then((folder) => 
    console.log(`The folder ->>`, JSON.stringify(folder, null, 4));
  )
  .catch((err) => console.log(`Folder error: ${err}`));
```

With it, I get the following errors: 
```
enterprise err -> Error: Unexpected API Response [403 Forbidden | 40ufgfgfuojdbhx5.0b1c0dc0a923ffa96d5e940bb0e9d0d48] access_denied_insufficient_permissions - Access denied - insufficient permission
index.js:9
Folder error: Error: Unexpected API Response [403 Forbidden | dy07v4gfuojdbzpt.0fbfcd3eff135889c54fb09ee561b27b1] access_denied_insufficient_permissions - Access denied - insufficient permission
```

Without it (i.e. if I _don't_ do `.asUser()`, I get an error only on the `Folder`:
```
Folder error: Error: Unexpected API Response [404 Not Found | f0o8sdgfuolcwrfm.069a1adb348ff1edfe0df8b30fe671863] not_found - Not Found
```

In that case, I get the following results though: 
```
users --> {
    "total_count": 0,
    "entries": [],
    "limit": 100,
    "offset": 0
}
index.js:8
current user details from Box: {
    "type": "user",
    "id": "12995640718",
    "name": "daily-leads-report",
    "login": "AutomationUser_1300875_GUXy98WENx@boxdevedition.com",
    "created_at": "2020-06-12T14:35:54-07:00",
    "modified_at": "2020-06-12T14:36:00-07:00",
    "language": "en",
    "timezone": "America/Los_Angeles",
    "space_amount": 10737418240,
    "space_used": 0,
    "max_upload_size": 2147483648,
    "status": "active",
    "job_title": "",
    "phone": "",
    "address": "",
    "avatar_url": "https://app.box.com/api/avatar/large/12995640718",
    "notification_email": []
}
```
The `name` is the name of the `custom app` I have on Box. (Where are the users though? Shouldn't there be at _least_ one user for my user?)

![Screen Shot 2020-06-16 at 1 18 01 PM](https://user-images.githubusercontent.com/39878535/84812372-f1541080-afd3-11ea-8148-4580c7355c97.png)

It's very possible that the issue is the app's not "authorized" -- but if that's the case, I have to admit, I find the documentation difficult to follow.
