### ISSUE TITLE
 PREVIEWER UPLOADER collaboration to folder

### ISSUE THREAD

**Issue by MartinRoman7** [box/box-node-sdk#449] opened 2019-12-02 18:59 UTC
I'm trying to add a **PREVIEWER UPLOADER** collaboration to a Box folder using Node SDK.

Currently, I can create a folder with **UPLOADER** collaboration.

```
appUserClient.collaborations.createWithUserEmail(asistentes[i].email,id_nFolder,appUserClient.collaborationRoles.UPLOADER)
```

So, my question is about how to chande **UPLOADER** collaboration to **PREVIEWER UPLOADER **

I tried the following statement but I get an error, maybe because exists a space.

```


Regards
appUserClient.collaborations.createWithUserEmail(asistentes[i].email,id_nFolder,appUserClient.collaborationRoles.PREVIEWER UPLOADER)
```

**Comment by mattwiller** [comment] 2019-12-04 00:27
@MartinRoman7 You're correct, the issue is that you have a space instead of an underscore.  The correct way to access this constant would be `appUserClient.collaborationRoles.PREVIEWER_UPLOADER`

**Comment by MartinRoman7** [comment] 2019-12-05 18:35
@mattwiller Thanks a lot.

**Comment by PJSimon** [comment] 2020-01-07 05:15
@MartinRoman7 I'm closing this as it appears resolved.  If that's not the case, please feel free to re-open!

**Closed by PJSimon** 2020-01-07 05:15 UTC
